#!/bin/bash
installdir=~/.config/nvim

echo "[*] creating NeoVim configuration at $installdir"
mkdir -p "$installdir"
cp -R src/* "$installdir"

echo "[*] installing plugins"
curl -fLo "${installdir}/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +PlugInstall +qall

echo "[*] adding alias from vi[m] -> nvim"
echo "alias vi=nvim" >> ~/.bash_aliases.local
echo "alias vim=nvim" >> ~/.bash_aliases.local

echo "[*] done"
